.PHONY: all
all:
	@$(SH) ./project.py -a viewer
	@$(SH) ./project.py -a capri -o advanced
	@$(SH) ./project.py -a flight -o advanced
	@$(SH) ./project.py -a webplayer -b combine -o advanced
	@$(SH) ./project.py -a firstperson -o advanced
	@$(SH) ./project.py -a fashion -o advanced
	@$(SH) ./project.py -a gallery -o advanced
	@$(SH) ./project.py -a new_year -o simple

# vim: set noet ts=4 sw=4:
